In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [4]:
df = pd.read_csv(r'C:\Users\earth\Desktop\class_folder\FinalProject\Resources\final_table.csv')
df.head()

,Date,Year,County,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,median_square_feet,average_listing_price,total_listing_count,violent_crime_rate,30_Year_Fixed_Rate,Number_of_Schools,median_listing_price_mm,Number_of_Parks
0,2022-06,2022,Cherokee,362500.0,271.0,38.0,148.0,8.0,76.0,1904.0,407510.0,467.0,NaN,5.52,NaN,-0.052164,2.0
1,2022-06,2022,Craven,313500.0,154.0,36.0,196.0,12.0,48.0,1927.0,396716.0,581.0,NaN,5.52,NaN,0.039801,63.0
2,2022-06,2022,Catawba,342450.0,207.0,34.0,224.0,0.0,96.0,1923.0,521108.0,508.0,NaN,5.52,NaN,-0.042098,65.0
3,2022-06,2022,Gaston,330000.0,283.0,30.0,412.0,12.0,200.0,1668.0,377406.0,828.0,NaN,5.52,NaN,0.039370,99.0
4,2022-06,2022,Warren,275000.0,19.0,68.0,12.0,0.0,4.0,1824.0,419452.0,29.0,NaN,5.52,NaN,NaN,1.0

In [5]:
df['violent_crime_rate']= df['violent_crime_rate'].str.replace(',','').astype(float)
df.head()

,Date,Year,County,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,median_square_feet,average_listing_price,total_listing_count,violent_crime_rate,30_Year_Fixed_Rate,Number_of_Schools,median_listing_price_mm,Number_of_Parks
0,2022-06,2022,Cherokee,362500.0,271.0,38.0,148.0,8.0,76.0,1904.0,407510.0,467.0,NaN,5.52,NaN,-0.052164,2.0
1,2022-06,2022,Craven,313500.0,154.0,36.0,196.0,12.0,48.0,1927.0,396716.0,581.0,NaN,5.52,NaN,0.039801,63.0
2,2022-06,2022,Catawba,342450.0,207.0,34.0,224.0,0.0,96.0,1923.0,521108.0,508.0,NaN,5.52,NaN,-0.042098,65.0
3,2022-06,2022,Gaston,330000.0,283.0,30.0,412.0,12.0,200.0,1668.0,377406.0,828.0,NaN,5.52,NaN,0.039370,99.0
4,2022-06,2022,Warren,275000.0,19.0,68.0,12.0,0.0,4.0,1824.0,419452.0,29.0,NaN,5.52,NaN,NaN,1.0

In [6]:
df_new1 = df.drop(['Date'], axis=1)
df_new1.dtypes

Year                         int64
County                      object
median_listing_price       float64
active_listing_count       float64
median_days_on_market      float64
new_listing_count          float64
price_increased_count      float64
price_reduced_count        float64
median_square_feet         float64
average_listing_price      float64
total_listing_count        float64
violent_crime_rate         float64
30_Year_Fixed_Rate         float64
Number_of_Schools          float64
median_listing_price_mm    float64
Number_of_Parks            float64
dtype: object

In [7]:
filter_df = df_new1[df_new1['Year'] <2019]
#filter_df["Year"].unique()
filter_df.head()

,Year,County,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,median_square_feet,average_listing_price,total_listing_count,violent_crime_rate,30_Year_Fixed_Rate,Number_of_Schools,median_listing_price_mm,Number_of_Parks
4196,2018,Wilkes,224000.0,306.0,126.0,52.0,0.0,28.0,2174.0,352753.0,340.0,243.6,4.64,53.0,-0.025663,34.0
4197,2018,Caswell,253900.0,52.0,183.0,0.0,0.0,4.0,1942.0,354254.0,52.0,NaN,4.64,47.0,NaN,37.0
4198,2018,Forsyth,245000.0,1197.0,85.0,296.0,12.0,204.0,2234.0,325987.0,1445.0,660.2,4.64,354.0,-0.019608,479.0
4199,2018,Surry,179900.0,145.0,114.0,28.0,0.0,24.0,1987.0,235683.0,176.0,89.0,4.64,45.0,-0.024403,13.0
4200,2018,Cherokee,199000.0,545.0,132.0,48.0,0.0,52.0,1708.0,264228.0,547.0,272.1,4.64,26.0,-0.004502,2.0

In [8]:

columns = [
     "Year", "County",'median_listing_price',
    "active_listing_count", "median_days_on_market", "new_listing_count",
    "price_increased_count", "price_reduced_count", "median_square_feet",
    "total_listing_count", "violent_crime_rate","Number_of_Parks",
    "Number_of_Schools","30_Year_Fixed_Rate"]

target = ["median_listing_price"]

In [9]:
# Load the data

df_data = filter_df.loc[:, columns].copy()
df_data = df_data.dropna()

df_data.reset_index(inplace=True, drop=True)

df_data.head()
df_data.isnull().sum()

Year                     0
County                   0
median_listing_price     0
active_listing_count     0
median_days_on_market    0
new_listing_count        0
price_increased_count    0
price_reduced_count      0
median_square_feet       0
total_listing_count      0
violent_crime_rate       0
Number_of_Parks          0
Number_of_Schools        0
30_Year_Fixed_Rate       0
dtype: int64

Split the Data into Training and Testing

In [10]:
# Create our features
X = df_data.drop('median_listing_price', axis=1)

X = pd.get_dummies(X)

# Create our target
y = df_data.loc[:, target].copy()

In [11]:
# Check the balance of our target values
y.value_counts()

median_listing_price
199900.0                34
179900.0                28
139900.0                27
249900.0                26
189900.0                25
                        ..
243900.0                 1
244450.0                 1
244608.0                 1
244900.0                 1
74900.0                  1
Length: 1231, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1) 
                                                 
X_test.shape

(653, 104)

Balanced Random Forest Regressor¶

In [13]:
#https://scikit-learn.org/0.16/modules/generated/sklearn.ensemble.RandomForestRegressor.html
# Set up 
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(n_estimators=1000, random_state=1) 
rf_model = rf_model.fit(X_train, y_train)
Counter(y_train['median_listing_price'])

Counter({174900.0: 12,
         277400.0: 1,
         198490.0: 1,
         163400.0: 1,
         94900.0: 2,
         128500.0: 2,
         179500.0: 3,
         205000.0: 3,
         197950.0: 1,
         149900.0: 16,
         189900.0: 16,
         339000.0: 4,
         117500.0: 1,
         239900.0: 12,
         169900.0: 14,
         376900.0: 1,
         179900.0: 21,
         219000.0: 2,
         385000.0: 4,
         199950.0: 3,
         129900.0: 19,
         218950.0: 2,
         340572.0: 1,
         129700.0: 2,
         245000.0: 5,
         224900.0: 5,
         164900.0: 12,
         158000.0: 2,
         372450.0: 2,
         148450.0: 1,
         300000.0: 5,
         232450.0: 2,
         199900.0: 23,
         217000.0: 3,
         298000.0: 4,
         299000.0: 21,
         171900.0: 1,
         266500.0: 3,
         269900.0: 8,
         161950.0: 3,
         279450.0: 3,
         273750.0: 2,
         264000.0: 1,
         375000.0: 9,
         143950.0: 1,
         124000.0: 3,
         417000.0: 3,
         189000.0: 12,
         338083.0: 1,
         275000.0: 19,
         195000.0: 4,
         179000.0: 5,
         279900.0: 12,
         99800.0: 1,
         399000.0: 18,
         459900.0: 1,
         139500.0: 4,
         165000.0: 5,
         289900.0: 10,
         194900.0: 4,
         424900.0: 1,
         400000.0: 6,
         89000.0: 2,
         348000.0: 2,
         163700.0: 1,
         389479.0: 1,
         489000.0: 2,
         269000.0: 6,
         299900.0: 16,
         99250.0: 1,
         176695.0: 1,
         98500.0: 2,
         164950.0: 3,
         322900.0: 1,
         121745.0: 1,
         168900.0: 1,
         199000.0: 4,
         411495.0: 1,
         128950.0: 1,
         118750.0: 1,
         346450.0: 1,
         414900.0: 2,
         239000.0: 12,
         238000.0: 2,
         153950.0: 1,
         144900.0: 6,
         159000.0: 7,
         253950.0: 1,
         220000.0: 3,
         215000.0: 7,
         392405.0: 1,
         201700.0: 1,
         127000.0: 1,
         294000.0: 3,
         171000.0: 2,
         289700.0: 2,
         84700.0: 1,
         272400.0: 1,
         399450.0: 2,
         184950.0: 4,
         299450.0: 1,
         134900.0: 7,
         240000.0: 1,
         284900.0: 3,
         309000.0: 4,
         284990.0: 1,
         188745.0: 1,
         262500.0: 1,
         197500.0: 2,
         139000.0: 11,
         249500.0: 2,
         324900.0: 1,
         410000.0: 2,
         154900.0: 5,
         160000.0: 1,
         119900.0: 11,
         310700.0: 1,
         123900.0: 1,
         102000.0: 2,
         302500.0: 2,
         244608.0: 1,
         204900.0: 2,
         122600.0: 1,
         249900.0: 20,
         350000.0: 4,
         252450.0: 1,
         227400.0: 1,
         99000.0: 6,
         305500.0: 1,
         299990.0: 1,
         419900.0: 2,
         160250.0: 1,
         391000.0: 2,
         124950.0: 1,
         398800.0: 1,
         265000.0: 4,
         393000.0: 1,
         152900.0: 2,
         129750.0: 3,
         179950.0: 3,
         229000.0: 10,
         239950.0: 2,
         135500.0: 1,
         207000.0: 1,
         249000.0: 12,
         192500.0: 2,
         99900.0: 9,
         442450.0: 1,
         218450.0: 2,
         155975.0: 1,
         214750.0: 1,
         286142.0: 2,
         96900.0: 4,
         182500.0: 2,
         79900.0: 4,
         249200.0: 1,
         287000.0: 1,
         98950.0: 1,
         280000.0: 5,
         134500.0: 2,
         195450.0: 3,
         281714.0: 1,
         397400.0: 1,
         236500.0: 1,
         402139.0: 1,
         184900.0: 7,
         319990.0: 1,
         309900.0: 3,
         298200.0: 1,
         160900.0: 1,
         210000.0: 5,
         127450.0: 1,
         309950.0: 1,
         192350.0: 1,
         332200.0: 1,
         395000.0: 5,
         234000.0: 1,
         388500.0: 1,
         236250.0: 1,
         198250.0: 1,
         219900.0: 8,
         394000.0: 2,
         278000.0: 1,
         141000.0: 2,
         238900.0: 1,
         338500.0: 1,
         369000.0: 1,
         123700.0: 1,
         443500.0: 1,
         141400.0: 1,
         319000.0: 2,
         147000.0: 4,
         95000.0: 3,
         431700.0: 1,
         415000.0: 1,
         177750.0: 1,
         123000.0: 3,
         289950.0: 1,
         140400.0: 1,
         98000.0: 2,
         185950.0: 3,
         193670.0: 1,
         97000.0: 2,
         189700.0: 3,
         219450.0: 2,
         327500.0: 2,
         189990.0: 1,
         129000.0: 4,
         167000.0: 2,
         159250.0: 1,
         137450.0: 2,
         340000.0: 3,
         149000.0: 4,
         190000.0: 7,
         241400.0: 1,
         99500.0: 1,
         342450.0: 1,
         381950.0: 1,
         273700.0: 1,
         182000.0: 1,
         392950.0: 1,
         218400.0: 1,
         175450.0: 1,
         374426.0: 1,
         128900.0: 1,
         181995.0: 1,
         279750.0: 1,
         292500.0: 2,
         195750.0: 2,
         214950.0: 4,
         154950.0: 1,
         132900.0: 1,
         220500.0: 1,
         184000.0: 2,
         217450.0: 5,
         175900.0: 3,
         419450.0: 2,
         194700.0: 1,
         189450.0: 3,
         259000.0: 1,
         302475.0: 1,
         212400.0: 1,
         254900.0: 2,
         188250.0: 1,
         74950.0: 1,
         430000.0: 1,
         139900.0: 17,
         399500.0: 1,
         274950.0: 2,
         172400.0: 2,
         259900.0: 10,
         172500.0: 1,
         295000.0: 5,
         349900.0: 5,
         173700.0: 3,
         197250.0: 2,
         102950.0: 1,
         292450.0: 2,
         225000.0: 6,
         261950.0: 1,
         392450.0: 2,
         235500.0: 1,
         191700.0: 1,
         293900.0: 1,
         88250.0: 1,
         225900.0: 1,
         168500.0: 1,
         142165.0: 1,
         128000.0: 1,
         149500.0: 2,
         269046.0: 1,
         324950.0: 3,
         354950.0: 1,
         167400.0: 1,
         389900.0: 2,
         425000.0: 8,
         341500.0: 1,
         288750.0: 2,
         159450.0: 6,
         372000.0: 1,
         345900.0: 2,
         129298.0: 1,
         199700.0: 3,
         109900.0: 6,
         183990.0: 1,
         397000.0: 2,
         188400.0: 1,
         172900.0: 4,
         399900.0: 8,
         207400.0: 1,
         276950.0: 2,
         161200.0: 1,
         267945.0: 1,
         220400.0: 1,
         364700.0: 1,
         379900.0: 2,
         163500.0: 1,
         274000.0: 1,
         125000.0: 5,
         549000.0: 2,
         326750.0: 1,
         326990.0: 1,
         188700.0: 1,
         274500.0: 1,
         116900.0: 1,
         134950.0: 1,
         289500.0: 4,
         189250.0: 1,
         360000.0: 1,
         177990.0: 1,
         142900.0: 1,
         274900.0: 7,
         297000.0: 4,
         359700.0: 1,
         238800.0: 1,
         307566.0: 1,
         448750.0: 1,
         179250.0: 1,
         260000.0: 3,
         240950.0: 1,
         326950.0: 1,
         168000.0: 1,
         175000.0: 7,
         93450.0: 1,
         142450.0: 3,
         197700.0: 1,
         169490.0: 1,
         285172.0: 1,
         186250.0: 1,
         440813.0: 1,
         201605.0: 1,
         308750.0: 1,
         264900.0: 4,
         439900.0: 1,
         195500.0: 1,
         149750.0: 1,
         277200.0: 1,
         199500.0: 6,
         148000.0: 4,
         192400.0: 2,
         150000.0: 7,
         174950.0: 1,
         224800.0: 1,
         376052.0: 1,
         300500.0: 1,
         279000.0: 8,
         171450.0: 1,
         161450.0: 2,
         159900.0: 13,
         162000.0: 1,
         227450.0: 1,
         160490.0: 1,
         113900.0: 1,
         282500.0: 2,
         325000.0: 6,
         104500.0: 1,
         129500.0: 4,
         231950.0: 1,
         224000.0: 2,
         204925.0: 1,
         180950.0: 1,
         434900.0: 2,
         122000.0: 1,
         418891.0: 1,
         157500.0: 1,
         279500.0: 2,
         245745.0: 1,
         107750.0: 1,
         165950.0: 2,
         190623.0: 1,
         301440.0: 1,
         449000.0: 1,
         182995.0: 3,
         198950.0: 2,
         296450.0: 1,
         278700.0: 2,
         295700.0: 1,
         177000.0: 2,
         189500.0: 2,
         176500.0: 1,
         269700.0: 1,
         129450.0: 1,
         139450.0: 3,
         266450.0: 1,
         303950.0: 1,
         389450.0: 1,
         178900.0: 3,
         314900.0: 1,
         348500.0: 2,
         189950.0: 3,
         234900.0: 4,
         405923.0: 1,
         191200.0: 1,
         138900.0: 1,
         213975.0: 1,
         191250.0: 1,
         382450.0: 1,
         145590.0: 1,
         171740.0: 1,
         122950.0: 1,
         357516.0: 1,
         304000.0: 1,
         377000.0: 3,
         126500.0: 1,
         250000.0: 5,
         324500.0: 1,
         282000.0: 3,
         257450.0: 1,
         341750.0: 1,
         139995.0: 1,
         169450.0: 6,
         155990.0: 1,
         238157.0: 1,
         539900.0: 1,
         183500.0: 2,
         136200.0: 2,
         98750.0: 2,
         119000.0: 4,
         384900.0: 2,
         277500.0: 2,
         137750.0: 1,
         162400.0: 2,
         399950.0: 2,
         285000.0: 7,
         169839.0: 1,
         443250.0: 1,
         260950.0: 2,
         142500.0: 3,
         429900.0: 2,
         373500.0: 1,
         317450.0: 1,
         259250.0: 1,
         203250.0: 1,
         160950.0: 1,
         226950.0: 1,
         212500.0: 1,
         189945.0: 1,
         194750.0: 1,
         128745.0: 1,
         209900.0: 4,
         192000.0: 4,
         394475.0: 1,
         195250.0: 1,
         292000.0: 2,
         337000.0: 1,
         267450.0: 2,
         254500.0: 1,
         215450.0: 1,
         137000.0: 1,
         349950.0: 3,
         424750.0: 2,
         170000.0: 3,
         227000.0: 5,
         169639.0: 1,
         274450.0: 2,
         360450.0: 1,
         212600.0: 1,
         434950.0: 1,
         355000.0: 2,
         349500.0: 2,
         267338.0: 1,
         329700.0: 1,
         299999.0: 2,
         277450.0: 3,
         299500.0: 5,
         232500.0: 1,
         152990.0: 2,
         200000.0: 6,
         197990.0: 1,
         266950.0: 1,
         98400.0: 1,
         290750.0: 1,
         394450.0: 1,
         246290.0: 1,
         279700.0: 2,
         242500.0: 2,
         179695.0: 1,
         299980.0: 1,
         187450.0: 3,
         152450.0: 1,
         389000.0: 7,
         419750.0: 1,
         249950.0: 2,
         218700.0: 1,
         346500.0: 2,
         281900.0: 1,
         419000.0: 1,
         180900.0: 1,
         406863.0: 1,
         174800.0: 2,
         262900.0: 1,
         317000.0: 1,
         127700.0: 1,
         290715.0: 1,
         347500.0: 1,
         302745.0: 1,
         228500.0: 1,
         214900.0: 3,
         294990.0: 1,
         268900.0: 3,
         304900.0: 2,
         284000.0: 2,
         284500.0: 3,
         335000.0: 2,
         518121.0: 1,
         234450.0: 1,
         206200.0: 1,
         229950.0: 1,
         299200.0: 1,
         279950.0: 1,
         198000.0: 2,
         138450.0: 1,
         184700.0: 1,
         329900.0: 3,
         135950.0: 1,
         194250.0: 1,
         347000.0: 3,
         265700.0: 1,
         422391.0: 1,
         88500.0: 1,
         205500.0: 2,
         139250.0: 1,
         124900.0: 2,
         214450.0: 1,
         196200.0: 1,
         308174.0: 1,
         130000.0: 4,
         389950.0: 2,
         289450.0: 1,
         254400.0: 1,
         196900.0: 1,
         225200.0: 1,
         328266.0: 1,
         244500.0: 2,
         139898.0: 1,
         198500.0: 1,
         198900.0: 3,
         168695.0: 1,
         475000.0: 1,
         407874.0: 1,
         144500.0: 2,
         374900.0: 2,
         259450.0: 1,
         211750.0: 1,
         297900.0: 2,
         439500.0: 1,
         178400.0: 1,
         237000.0: 5,
         257400.0: 2,
         261450.0: 1,
         195200.0: 1,
         328000.0: 1,
         161700.0: 1,
         257700.0: 1,
         365000.0: 2,
         349000.0: 3,
         293495.0: 1,
         246134.0: 1,
         164450.0: 1,
         85900.0: 1,
         95700.0: 1,
         115000.0: 2,
         142000.0: 2,
         369950.0: 1,
         277000.0: 2,
         404153.0: 1,
         399250.0: 1,
         117000.0: 1,
         310500.0: 1,
         121500.0: 1,
         224950.0: 1,
         439000.0: 5,
         288000.0: 3,
         197900.0: 2,
         267250.0: 1,
         216950.0: 1,
         366513.0: 1,
         322450.0: 1,
         414000.0: 1,
         319544.0: 1,
         162900.0: 1,
         447500.0: 1,
         178745.0: 1,
         357448.0: 1,
         153500.0: 1,
         259700.0: 2,
         131950.0: 1,
         132200.0: 3,
         149200.0: 1,
         299950.0: 4,
         440000.0: 1,
         186400.0: 1,
         99850.0: 2,
         139777.0: 1,
         392500.0: 1,
         276000.0: 1,
         179750.0: 1,
         405000.0: 2,
         185000.0: 8,
         277945.0: 1,
         359900.0: 1,
         235000.0: 2,
         269999.0: 1,
         278772.0: 1,
         359000.0: 1,
         430250.0: 1,
         222200.0: 1,
         162245.0: 1,
         180500.0: 1,
         179450.0: 1,
         449900.0: 1,
         319700.0: 1,
         148750.0: 1,
         229500.0: 2,
         319500.0: 1,
         429000.0: 11,
         88400.0: 1,
         223700.0: 1,
         192450.0: 1,
         117200.0: 2,
         154450.0: 1,
         369925.0: 1,
         379000.0: 2,
         369450.0: 1,
         229900.0: 4,
         308000.0: 1,
         298850.0: 1,
         390393.0: 1,
         260495.0: 1,
         370850.0: 1,
         289000.0: 10,
         339700.0: 1,
         269500.0: 1,
         158450.0: 1,
         369900.0: 2,
         266000.0: 1,
         207900.0: 1,
         399400.0: 2,
         318750.0: 1,
         325495.0: 1,
         384150.0: 1,
         229700.0: 1,
         122450.0: 1,
         222450.0: 1,
         181950.0: 1,
         334950.0: 1,
         243824.0: 1,
         164000.0: 1,
         330552.0: 1,
         191900.0: 1,
         184400.0: 1,
         234950.0: 2,
         294950.0: 1,
         247378.0: 1,
         424500.0: 2,
         177150.0: 1,
         281445.0: 1,
         299700.0: 1,
         332000.0: 1,
         194000.0: 3,
         243900.0: 1,
         295450.0: 1,
         135000.0: 4,
         152768.0: 1,
         332500.0: 1,
         89900.0: 3,
         204950.0: 1,
         187500.0: 2,
         494440.0: 1,
         232000.0: 3,
         384950.0: 1,
         422450.0: 1,
         415900.0: 1,
         427000.0: 1,
         147500.0: 2,
         145750.0: 1,
         248900.0: 1,
         212250.0: 1,
         193000.0: 1,
         131000.0: 2,
         281000.0: 1,
         182450.0: 1,
         127900.0: 1,
         244000.0: 1,
         290000.0: 2,
         161900.0: 1,
         246150.0: 1,
         104950.0: 1,
         409900.0: 1,
         325285.0: 1,
         326200.0: 1,
         217350.0: 1,
         182150.0: 1,
         228000.0: 1,
         255848.0: 1,
         348700.0: 1,
         173950.0: 1,
         264450.0: 1,
         304038.0: 1,
         383370.0: 1,
         433352.0: 1,
         270450.0: 1,
         380000.0: 1,
         157950.0: 1,
         325056.0: 1,
         145450.0: 2,
         246200.0: 1,
         169000.0: 3,
         82400.0: 1,
         249700.0: 2,
         297625.0: 1,
         132000.0: 1,
         309500.0: 1,
         283675.0: 1,
         188900.0: 1,
         182600.0: 1,
         236445.0: 1,
         74900.0: 1,
         398500.0: 3,
         235518.0: 1,
         134200.0: 1,
         221950.0: 1,
         243700.0: 1,
         269450.0: 3,
         119990.0: 1,
         159950.0: 2,
         140450.0: 1,
         214000.0: 2,
         233490.0: 1,
         147900.0: 3,
         270000.0: 2,
         144389.0: 1,
         276800.0: 1,
         289626.0: 1,
         417250.0: 1,
         389929.0: 1,
         187400.0: 1,
         229423.0: 1,
         231500.0: 1,
         162450.0: 1,
         423590.0: 1,
         101000.0: 1,
         276437.0: 1,
         246450.0: 1,
         252300.0: 1,
         133950.0: 1,
         193400.0: 1,
         265900.0: 1,
         397500.0: 1,
         216000.0: 2,
         544400.0: 1,
         304990.0: 1,
         344975.0: 1,
         169500.0: 1,
         263950.0: 1,
         133000.0: 1,
         145000.0: 1,
         201500.0: 1,
         290850.0: 1,
         239500.0: 2,
         152850.0: 1,
         196400.0: 1,
         186500.0: 1,
         219500.0: 1,
         183490.0: 1,
         272000.0: 2,
         527450.0: 1,
         354900.0: 1,
         499950.0: 1,
         271500.0: 1,
         174400.0: 1,
         239450.0: 3,
         235950.0: 1,
         392495.0: 1,
         105900.0: 1,
         440950.0: 1,
         241000.0: 1,
         209000.0: 1,
         268500.0: 1,
         256945.0: 1,
         88900.0: 1,
         349450.0: 1,
         98450.0: 1,
         180000.0: 2,
         86000.0: 1,
         152950.0: 2,
         263326.0: 1,
         123500.0: 1,
         186858.0: 1,
         397300.0: 1,
         290900.0: 1,
         184800.0: 1,
         228999.0: 1,
         211625.0: 1,
         319438.0: 1,
         157900.0: 1,
         500000.0: 1,
         211000.0: 1,
         282450.0: 1,
         249450.0: 2,
         224500.0: 1,
         186700.0: 1,
         93200.0: 1,
         87400.0: 1,
         167450.0: 1,
         422000.0: 1,
         125900.0: 1,
         123950.0: 1,
         478500.0: 1,
         92000.0: 1,
         396827.0: 1,
         314500.0: 1,
         373490.0: 1,
         324750.0: 1,
         253250.0: 1,
         179498.0: 1,
         329000.0: 1,
         237500.0: 1,
         280900.0: 3,
         332970.0: 1,
         75000.0: 1,
         166400.0: 1,
         148900.0: 2,
         287900.0: 1,
         274300.0: 1,
         206585.0: 1,
         177250.0: 1,
         233750.0: 1,
         165490.0: 1,
         152495.0: 1,
         317475.0: 1,
         426250.0: 1,
         133750.0: 1,
         296250.0: 1,
         148500.0: 1,
         156500.0: 1,
         140750.0: 1,
         203450.0: 1,
         227700.0: 1,
         309750.0: 1,
         374495.0: 1,
         328200.0: 1,
         151450.0: 1,
         201724.0: 1,
         438620.0: 1,
         184445.0: 1,
         382353.0: 1,
         176200.0: 1,
         198400.0: 1,
         347900.0: 1,
         243000.0: 1,
         92500.0: 2,
         187700.0: 1,
         114900.0: 1,
         188000.0: 1,
         244450.0: 1,
         220450.0: 1,
         248990.0: 1,
         360548.0: 1,
         89450.0: 1,
         164250.0: 1,
         237990.0: 1,
         191950.0: 1,
         147490.0: 1,
         143700.0: 2,
         450000.0: 1,
         244950.0: 2,
         407158.0: 1,
         274768.0: 1,
         211700.0: 1,
         167500.0: 1,
         174700.0: 1,
         126000.0: 1,
         89995.0: 1,
         111750.0: 1,
         214500.0: 1,
         176900.0: 1,
         413750.0: 1,
         144750.0: 1,
         247923.0: 1,
         268000.0: 1,
         292115.0: 1,
         260700.0: 1,
         256248.0: 1,
         177700.0: 1,
         319900.0: 1,
         237200.0: 1,
         152500.0: 1,
         398000.0: 2,
         171500.0: 1,
         362000.0: 1,
         335195.0: 1,
         154750.0: 1,
         119450.0: 1,
         177200.0: 1,
         196000.0: 1,
         354726.0: 1,
         249940.0: 1,
         324495.0: 1,
         192900.0: 1,
         371990.0: 1,
         291000.0: 1,
         264800.0: 1,
         394500.0: 1,
         394900.0: 1,
         307450.0: 1,
         281200.0: 1,
         197000.0: 1,
         122995.0: 1,

In [14]:
score = rf_model.score(X_train, y_train)
print(score)

0.9952781519616808

In [19]:
score = rf_model.score(X_test, y_test)
print(score)

0.9744152472208092

In [15]:
# List the features sorted in descending order by feature importance
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.520377287625235, 'median_square_feet'),
 (0.09181097987145881, 'violent_crime_rate'),
 (0.07814893954404825, 'Number_of_Schools'),
 (0.057212759971408594, 'total_listing_count'),
 (0.050089675233197475, 'active_listing_count'),
 (0.027547627463687694, 'Number_of_Parks'),
 (0.01948099724996908, 'County_Buncombe'),
 (0.013471265578081449, 'price_reduced_count'),
 (0.01124718837308971, 'County_Carteret'),
 (0.01113716821698794, 'median_days_on_market'),
 (0.010151420206572006, 'County_Dare'),
 (0.010068937715726606, 'County_Chatham'),
 (0.009221885343672952, '30_Year_Fixed_Rate'),
 (0.00632003747784434, 'new_listing_count'),
 (0.005214795604543163, 'price_increased_count'),
 (0.0051610626475961634, 'County_Orange'),
 (0.004774914365337093, 'County_Clay'),
 (0.004667674145809344, 'County_Davidson'),
 (0.004205870610072204, 'County_Henderson'),
 (0.0037293083093506057, 'Year'),
 (0.003630842809463058, 'County_Scotland'),
 (0.003554740713514208, 'County_Duplin'),
 (0.003451446794967715, 'County_Haywood'),
 (0.0030668218942052385, 'County_Hertford'),
 (0.0029979616467729242, 'County_Stanly'),
 (0.0023734384325692233, 'County_Durham'),
 (0.002340180212755104, 'County_Polk'),
 (0.0019078663077217524, 'County_Chowan'),
 (0.0018751612009361752, 'County_Swain'),
 (0.001793152010603459, 'County_Forsyth'),
 (0.0016594086711848287, 'County_Alleghany'),
 (0.0014214289282753632, 'County_Person'),
 (0.0013081059895359627, 'County_Graham'),
 (0.0012964349469537328, 'County_Pamlico'),
 (0.0012696095715298821, 'County_Surry'),
 (0.0011386765354060725, 'County_Jackson'),
 (0.0010941912299014694, 'County_Rutherford'),
 (0.0010707711078370345, 'County_Bertie'),
 (0.0010632811268627288, 'County_Macon'),
 (0.0009976225913218716, 'County_Beaufort'),
 (0.0009491426235326544, 'County_Davie'),
 (0.0009473575254738074, 'County_Columbus'),
 (0.0009046253604367594, 'County_Brunswick'),
 (0.0008418771514249037, 'County_Currituck'),
 (0.0006356811169346923, 'County_Onslow'),
 (0.0006035252000449144, 'County_Yadkin'),
 (0.0005643737802216815, 'County_Cherokee'),
 (0.0005436279232314482, 'County_Halifax'),
 (0.000538384793745434, 'County_Transylvania'),
 (0.0004671517091180235, 'County_Madison'),
 (0.0004636517267459709, 'County_Mecklenburg'),
 (0.0004262287864335201, 'County_Montgomery'),
 (0.00040349352099275663, 'County_Lincoln'),
 (0.0003977836539481987, 'County_Wilkes'),
 (0.000380357448898316, 'County_Catawba'),
 (0.0003659496030557953, 'County_Martin'),
 (0.0003257567078701153, 'County_Cabarrus'),
 (0.0003180788116682428, 'County_Perquimans'),
 (0.0003077628665934187, 'County_Vance'),
 (0.00030459891694254425, 'County_Cumberland'),
 (0.0003040817153561581, 'County_Stokes'),
 (0.00030032816440960034, 'County_Moore'),
 (0.0002953577884499509, 'County_Rockingham'),
 (0.00028749561052386955, 'County_Edgecombe'),
 (0.0002829367100422652, 'County_Pasquotank'),
 (0.00028095068101760773, 'County_Franklin'),
 (0.0002705387968219789, 'County_Pender'),
 (0.0002646184690539683, 'County_Lee'),
 (0.00021593341363902572, 'County_Hoke'),
 (0.00020962052521294043, 'County_Avery'),
 (0.00019683369003488905, 'County_Caswell'),
 (0.0001953328236793459, 'County_Northampton'),
 (0.00019393593094710774, 'County_Anson'),
 (0.0001812442589948385, 'County_Watauga'),
 (0.00017906508228789423, 'County_Craven'),
 (0.00017682848498111646, 'County_Warren'),
 (0.000164852742284077, 'County_Randolph'),
 (0.00016480482059170817, 'County_Alamance'),
 (0.00016458948309731647, 'County_Wilson'),
 (0.00015835914522731477, 'County_Cleveland'),
 (0.00014069320817174002, 'County_Alexander'),
 (0.00013411449137902803, 'County_Guilford'),
 (0.00012868185237475575, 'County_Sampson'),
 (0.00011306079022532585, 'County_Johnston'),
 (0.00010407097545320947, 'County_Harnett'),
 (9.620179883766089e-05, 'County_Richmond'),
 (8.874172153931759e-05, 'County_Yancey'),
 (8.453450136429937e-05, 'County_Pitt'),
 (7.931339628035985e-05, 'County_Burke'),
 (7.67307085586728e-05, 'County_Wayne'),
 (6.37440356522618e-05, 'County_Robeson'),
 (5.380896667634533e-05, 'County_Camden'),
 (5.3226139697438264e-05, 'County_Iredell'),
 (4.030048564804588e-05, 'County_Lenoir'),
 (3.8539710423639734e-05, 'County_Rowan'),
 (3.223609402902476e-05, 'County_Greene'),
 (2.7270244696060287e-05, 'County_Gaston'),
 (2.4075317509425262e-05, 'County_Union'),
 (2.241705862360834e-05, 'County_Tyrrell'),
 (1.8732016307777614e-05, 'County_Caldwell'),
 (1.830374982447631e-05, 'County_Granville'),
 (1.6826394121540164e-05, 'County_Ashe'),
 (1.3693459720177203e-05, 'County_Nash'),
 (2.6270429135005305e-06, 'County_Wake')]

# Hypertune features

In [16]:
# Resample the training data with the RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(n_estimators=1500, random_state=1) 
rf_model = rf_model.fit(X_train, y_train)
Counter(y_train['median_listing_price'])

Counter({174900.0: 12,
         277400.0: 1,
         198490.0: 1,
         163400.0: 1,
         94900.0: 2,
         128500.0: 2,
         179500.0: 3,
         205000.0: 3,
         197950.0: 1,
         149900.0: 16,
         189900.0: 16,
         339000.0: 4,
         117500.0: 1,
         239900.0: 12,
         169900.0: 14,
         376900.0: 1,
         179900.0: 21,
         219000.0: 2,
         385000.0: 4,
         199950.0: 3,
         129900.0: 19,
         218950.0: 2,
         340572.0: 1,
         129700.0: 2,
         245000.0: 5,
         224900.0: 5,
         164900.0: 12,
         158000.0: 2,
         372450.0: 2,
         148450.0: 1,
         300000.0: 5,
         232450.0: 2,
         199900.0: 23,
         217000.0: 3,
         298000.0: 4,
         299000.0: 21,
         171900.0: 1,
         266500.0: 3,
         269900.0: 8,
         161950.0: 3,
         279450.0: 3,
         273750.0: 2,
         264000.0: 1,
         375000.0: 9,
         143950.0: 1,
         124000.0: 3,
         417000.0: 3,
         189000.0: 12,
         338083.0: 1,
         275000.0: 19,
         195000.0: 4,
         179000.0: 5,
         279900.0: 12,
         99800.0: 1,
         399000.0: 18,
         459900.0: 1,
         139500.0: 4,
         165000.0: 5,
         289900.0: 10,
         194900.0: 4,
         424900.0: 1,
         400000.0: 6,
         89000.0: 2,
         348000.0: 2,
         163700.0: 1,
         389479.0: 1,
         489000.0: 2,
         269000.0: 6,
         299900.0: 16,
         99250.0: 1,
         176695.0: 1,
         98500.0: 2,
         164950.0: 3,
         322900.0: 1,
         121745.0: 1,
         168900.0: 1,
         199000.0: 4,
         411495.0: 1,
         128950.0: 1,
         118750.0: 1,
         346450.0: 1,
         414900.0: 2,
         239000.0: 12,
         238000.0: 2,
         153950.0: 1,
         144900.0: 6,
         159000.0: 7,
         253950.0: 1,
         220000.0: 3,
         215000.0: 7,
         392405.0: 1,
         201700.0: 1,
         127000.0: 1,
         294000.0: 3,
         171000.0: 2,
         289700.0: 2,
         84700.0: 1,
         272400.0: 1,
         399450.0: 2,
         184950.0: 4,
         299450.0: 1,
         134900.0: 7,
         240000.0: 1,
         284900.0: 3,
         309000.0: 4,
         284990.0: 1,
         188745.0: 1,
         262500.0: 1,
         197500.0: 2,
         139000.0: 11,
         249500.0: 2,
         324900.0: 1,
         410000.0: 2,
         154900.0: 5,
         160000.0: 1,
         119900.0: 11,
         310700.0: 1,
         123900.0: 1,
         102000.0: 2,
         302500.0: 2,
         244608.0: 1,
         204900.0: 2,
         122600.0: 1,
         249900.0: 20,
         350000.0: 4,
         252450.0: 1,
         227400.0: 1,
         99000.0: 6,
         305500.0: 1,
         299990.0: 1,
         419900.0: 2,
         160250.0: 1,
         391000.0: 2,
         124950.0: 1,
         398800.0: 1,
         265000.0: 4,
         393000.0: 1,
         152900.0: 2,
         129750.0: 3,
         179950.0: 3,
         229000.0: 10,
         239950.0: 2,
         135500.0: 1,
         207000.0: 1,
         249000.0: 12,
         192500.0: 2,
         99900.0: 9,
         442450.0: 1,
         218450.0: 2,
         155975.0: 1,
         214750.0: 1,
         286142.0: 2,
         96900.0: 4,
         182500.0: 2,
         79900.0: 4,
         249200.0: 1,
         287000.0: 1,
         98950.0: 1,
         280000.0: 5,
         134500.0: 2,
         195450.0: 3,
         281714.0: 1,
         397400.0: 1,
         236500.0: 1,
         402139.0: 1,
         184900.0: 7,
         319990.0: 1,
         309900.0: 3,
         298200.0: 1,
         160900.0: 1,
         210000.0: 5,
         127450.0: 1,
         309950.0: 1,
         192350.0: 1,
         332200.0: 1,
         395000.0: 5,
         234000.0: 1,
         388500.0: 1,
         236250.0: 1,
         198250.0: 1,
         219900.0: 8,
         394000.0: 2,
         278000.0: 1,
         141000.0: 2,
         238900.0: 1,
         338500.0: 1,
         369000.0: 1,
         123700.0: 1,
         443500.0: 1,
         141400.0: 1,
         319000.0: 2,
         147000.0: 4,
         95000.0: 3,
         431700.0: 1,
         415000.0: 1,
         177750.0: 1,
         123000.0: 3,
         289950.0: 1,
         140400.0: 1,
         98000.0: 2,
         185950.0: 3,
         193670.0: 1,
         97000.0: 2,
         189700.0: 3,
         219450.0: 2,
         327500.0: 2,
         189990.0: 1,
         129000.0: 4,
         167000.0: 2,
         159250.0: 1,
         137450.0: 2,
         340000.0: 3,
         149000.0: 4,
         190000.0: 7,
         241400.0: 1,
         99500.0: 1,
         342450.0: 1,
         381950.0: 1,
         273700.0: 1,
         182000.0: 1,
         392950.0: 1,
         218400.0: 1,
         175450.0: 1,
         374426.0: 1,
         128900.0: 1,
         181995.0: 1,
         279750.0: 1,
         292500.0: 2,
         195750.0: 2,
         214950.0: 4,
         154950.0: 1,
         132900.0: 1,
         220500.0: 1,
         184000.0: 2,
         217450.0: 5,
         175900.0: 3,
         419450.0: 2,
         194700.0: 1,
         189450.0: 3,
         259000.0: 1,
         302475.0: 1,
         212400.0: 1,
         254900.0: 2,
         188250.0: 1,
         74950.0: 1,
         430000.0: 1,
         139900.0: 17,
         399500.0: 1,
         274950.0: 2,
         172400.0: 2,
         259900.0: 10,
         172500.0: 1,
         295000.0: 5,
         349900.0: 5,
         173700.0: 3,
         197250.0: 2,
         102950.0: 1,
         292450.0: 2,
         225000.0: 6,
         261950.0: 1,
         392450.0: 2,
         235500.0: 1,
         191700.0: 1,
         293900.0: 1,
         88250.0: 1,
         225900.0: 1,
         168500.0: 1,
         142165.0: 1,
         128000.0: 1,
         149500.0: 2,
         269046.0: 1,
         324950.0: 3,
         354950.0: 1,
         167400.0: 1,
         389900.0: 2,
         425000.0: 8,
         341500.0: 1,
         288750.0: 2,
         159450.0: 6,
         372000.0: 1,
         345900.0: 2,
         129298.0: 1,
         199700.0: 3,
         109900.0: 6,
         183990.0: 1,
         397000.0: 2,
         188400.0: 1,
         172900.0: 4,
         399900.0: 8,
         207400.0: 1,
         276950.0: 2,
         161200.0: 1,
         267945.0: 1,
         220400.0: 1,
         364700.0: 1,
         379900.0: 2,
         163500.0: 1,
         274000.0: 1,
         125000.0: 5,
         549000.0: 2,
         326750.0: 1,
         326990.0: 1,
         188700.0: 1,
         274500.0: 1,
         116900.0: 1,
         134950.0: 1,
         289500.0: 4,
         189250.0: 1,
         360000.0: 1,
         177990.0: 1,
         142900.0: 1,
         274900.0: 7,
         297000.0: 4,
         359700.0: 1,
         238800.0: 1,
         307566.0: 1,
         448750.0: 1,
         179250.0: 1,
         260000.0: 3,
         240950.0: 1,
         326950.0: 1,
         168000.0: 1,
         175000.0: 7,
         93450.0: 1,
         142450.0: 3,
         197700.0: 1,
         169490.0: 1,
         285172.0: 1,
         186250.0: 1,
         440813.0: 1,
         201605.0: 1,
         308750.0: 1,
         264900.0: 4,
         439900.0: 1,
         195500.0: 1,
         149750.0: 1,
         277200.0: 1,
         199500.0: 6,
         148000.0: 4,
         192400.0: 2,
         150000.0: 7,
         174950.0: 1,
         224800.0: 1,
         376052.0: 1,
         300500.0: 1,
         279000.0: 8,
         171450.0: 1,
         161450.0: 2,
         159900.0: 13,
         162000.0: 1,
         227450.0: 1,
         160490.0: 1,
         113900.0: 1,
         282500.0: 2,
         325000.0: 6,
         104500.0: 1,
         129500.0: 4,
         231950.0: 1,
         224000.0: 2,
         204925.0: 1,
         180950.0: 1,
         434900.0: 2,
         122000.0: 1,
         418891.0: 1,
         157500.0: 1,
         279500.0: 2,
         245745.0: 1,
         107750.0: 1,
         165950.0: 2,
         190623.0: 1,
         301440.0: 1,
         449000.0: 1,
         182995.0: 3,
         198950.0: 2,
         296450.0: 1,
         278700.0: 2,
         295700.0: 1,
         177000.0: 2,
         189500.0: 2,
         176500.0: 1,
         269700.0: 1,
         129450.0: 1,
         139450.0: 3,
         266450.0: 1,
         303950.0: 1,
         389450.0: 1,
         178900.0: 3,
         314900.0: 1,
         348500.0: 2,
         189950.0: 3,
         234900.0: 4,
         405923.0: 1,
         191200.0: 1,
         138900.0: 1,
         213975.0: 1,
         191250.0: 1,
         382450.0: 1,
         145590.0: 1,
         171740.0: 1,
         122950.0: 1,
         357516.0: 1,
         304000.0: 1,
         377000.0: 3,
         126500.0: 1,
         250000.0: 5,
         324500.0: 1,
         282000.0: 3,
         257450.0: 1,
         341750.0: 1,
         139995.0: 1,
         169450.0: 6,
         155990.0: 1,
         238157.0: 1,
         539900.0: 1,
         183500.0: 2,
         136200.0: 2,
         98750.0: 2,
         119000.0: 4,
         384900.0: 2,
         277500.0: 2,
         137750.0: 1,
         162400.0: 2,
         399950.0: 2,
         285000.0: 7,
         169839.0: 1,
         443250.0: 1,
         260950.0: 2,
         142500.0: 3,
         429900.0: 2,
         373500.0: 1,
         317450.0: 1,
         259250.0: 1,
         203250.0: 1,
         160950.0: 1,
         226950.0: 1,
         212500.0: 1,
         189945.0: 1,
         194750.0: 1,
         128745.0: 1,
         209900.0: 4,
         192000.0: 4,
         394475.0: 1,
         195250.0: 1,
         292000.0: 2,
         337000.0: 1,
         267450.0: 2,
         254500.0: 1,
         215450.0: 1,
         137000.0: 1,
         349950.0: 3,
         424750.0: 2,
         170000.0: 3,
         227000.0: 5,
         169639.0: 1,
         274450.0: 2,
         360450.0: 1,
         212600.0: 1,
         434950.0: 1,
         355000.0: 2,
         349500.0: 2,
         267338.0: 1,
         329700.0: 1,
         299999.0: 2,
         277450.0: 3,
         299500.0: 5,
         232500.0: 1,
         152990.0: 2,
         200000.0: 6,
         197990.0: 1,
         266950.0: 1,
         98400.0: 1,
         290750.0: 1,
         394450.0: 1,
         246290.0: 1,
         279700.0: 2,
         242500.0: 2,
         179695.0: 1,
         299980.0: 1,
         187450.0: 3,
         152450.0: 1,
         389000.0: 7,
         419750.0: 1,
         249950.0: 2,
         218700.0: 1,
         346500.0: 2,
         281900.0: 1,
         419000.0: 1,
         180900.0: 1,
         406863.0: 1,
         174800.0: 2,
         262900.0: 1,
         317000.0: 1,
         127700.0: 1,
         290715.0: 1,
         347500.0: 1,
         302745.0: 1,
         228500.0: 1,
         214900.0: 3,
         294990.0: 1,
         268900.0: 3,
         304900.0: 2,
         284000.0: 2,
         284500.0: 3,
         335000.0: 2,
         518121.0: 1,
         234450.0: 1,
         206200.0: 1,
         229950.0: 1,
         299200.0: 1,
         279950.0: 1,
         198000.0: 2,
         138450.0: 1,
         184700.0: 1,
         329900.0: 3,
         135950.0: 1,
         194250.0: 1,
         347000.0: 3,
         265700.0: 1,
         422391.0: 1,
         88500.0: 1,
         205500.0: 2,
         139250.0: 1,
         124900.0: 2,
         214450.0: 1,
         196200.0: 1,
         308174.0: 1,
         130000.0: 4,
         389950.0: 2,
         289450.0: 1,
         254400.0: 1,
         196900.0: 1,
         225200.0: 1,
         328266.0: 1,
         244500.0: 2,
         139898.0: 1,
         198500.0: 1,
         198900.0: 3,
         168695.0: 1,
         475000.0: 1,
         407874.0: 1,
         144500.0: 2,
         374900.0: 2,
         259450.0: 1,
         211750.0: 1,
         297900.0: 2,
         439500.0: 1,
         178400.0: 1,
         237000.0: 5,
         257400.0: 2,
         261450.0: 1,
         195200.0: 1,
         328000.0: 1,
         161700.0: 1,
         257700.0: 1,
         365000.0: 2,
         349000.0: 3,
         293495.0: 1,
         246134.0: 1,
         164450.0: 1,
         85900.0: 1,
         95700.0: 1,
         115000.0: 2,
         142000.0: 2,
         369950.0: 1,
         277000.0: 2,
         404153.0: 1,
         399250.0: 1,
         117000.0: 1,
         310500.0: 1,
         121500.0: 1,
         224950.0: 1,
         439000.0: 5,
         288000.0: 3,
         197900.0: 2,
         267250.0: 1,
         216950.0: 1,
         366513.0: 1,
         322450.0: 1,
         414000.0: 1,
         319544.0: 1,
         162900.0: 1,
         447500.0: 1,
         178745.0: 1,
         357448.0: 1,
         153500.0: 1,
         259700.0: 2,
         131950.0: 1,
         132200.0: 3,
         149200.0: 1,
         299950.0: 4,
         440000.0: 1,
         186400.0: 1,
         99850.0: 2,
         139777.0: 1,
         392500.0: 1,
         276000.0: 1,
         179750.0: 1,
         405000.0: 2,
         185000.0: 8,
         277945.0: 1,
         359900.0: 1,
         235000.0: 2,
         269999.0: 1,
         278772.0: 1,
         359000.0: 1,
         430250.0: 1,
         222200.0: 1,
         162245.0: 1,
         180500.0: 1,
         179450.0: 1,
         449900.0: 1,
         319700.0: 1,
         148750.0: 1,
         229500.0: 2,
         319500.0: 1,
         429000.0: 11,
         88400.0: 1,
         223700.0: 1,
         192450.0: 1,
         117200.0: 2,
         154450.0: 1,
         369925.0: 1,
         379000.0: 2,
         369450.0: 1,
         229900.0: 4,
         308000.0: 1,
         298850.0: 1,
         390393.0: 1,
         260495.0: 1,
         370850.0: 1,
         289000.0: 10,
         339700.0: 1,
         269500.0: 1,
         158450.0: 1,
         369900.0: 2,
         266000.0: 1,
         207900.0: 1,
         399400.0: 2,
         318750.0: 1,
         325495.0: 1,
         384150.0: 1,
         229700.0: 1,
         122450.0: 1,
         222450.0: 1,
         181950.0: 1,
         334950.0: 1,
         243824.0: 1,
         164000.0: 1,
         330552.0: 1,
         191900.0: 1,
         184400.0: 1,
         234950.0: 2,
         294950.0: 1,
         247378.0: 1,
         424500.0: 2,
         177150.0: 1,
         281445.0: 1,
         299700.0: 1,
         332000.0: 1,
         194000.0: 3,
         243900.0: 1,
         295450.0: 1,
         135000.0: 4,
         152768.0: 1,
         332500.0: 1,
         89900.0: 3,
         204950.0: 1,
         187500.0: 2,
         494440.0: 1,
         232000.0: 3,
         384950.0: 1,
         422450.0: 1,
         415900.0: 1,
         427000.0: 1,
         147500.0: 2,
         145750.0: 1,
         248900.0: 1,
         212250.0: 1,
         193000.0: 1,
         131000.0: 2,
         281000.0: 1,
         182450.0: 1,
         127900.0: 1,
         244000.0: 1,
         290000.0: 2,
         161900.0: 1,
         246150.0: 1,
         104950.0: 1,
         409900.0: 1,
         325285.0: 1,
         326200.0: 1,
         217350.0: 1,
         182150.0: 1,
         228000.0: 1,
         255848.0: 1,
         348700.0: 1,
         173950.0: 1,
         264450.0: 1,
         304038.0: 1,
         383370.0: 1,
         433352.0: 1,
         270450.0: 1,
         380000.0: 1,
         157950.0: 1,
         325056.0: 1,
         145450.0: 2,
         246200.0: 1,
         169000.0: 3,
         82400.0: 1,
         249700.0: 2,
         297625.0: 1,
         132000.0: 1,
         309500.0: 1,
         283675.0: 1,
         188900.0: 1,
         182600.0: 1,
         236445.0: 1,
         74900.0: 1,
         398500.0: 3,
         235518.0: 1,
         134200.0: 1,
         221950.0: 1,
         243700.0: 1,
         269450.0: 3,
         119990.0: 1,
         159950.0: 2,
         140450.0: 1,
         214000.0: 2,
         233490.0: 1,
         147900.0: 3,
         270000.0: 2,
         144389.0: 1,
         276800.0: 1,
         289626.0: 1,
         417250.0: 1,
         389929.0: 1,
         187400.0: 1,
         229423.0: 1,
         231500.0: 1,
         162450.0: 1,
         423590.0: 1,
         101000.0: 1,
         276437.0: 1,
         246450.0: 1,
         252300.0: 1,
         133950.0: 1,
         193400.0: 1,
         265900.0: 1,
         397500.0: 1,
         216000.0: 2,
         544400.0: 1,
         304990.0: 1,
         344975.0: 1,
         169500.0: 1,
         263950.0: 1,
         133000.0: 1,
         145000.0: 1,
         201500.0: 1,
         290850.0: 1,
         239500.0: 2,
         152850.0: 1,
         196400.0: 1,
         186500.0: 1,
         219500.0: 1,
         183490.0: 1,
         272000.0: 2,
         527450.0: 1,
         354900.0: 1,
         499950.0: 1,
         271500.0: 1,
         174400.0: 1,
         239450.0: 3,
         235950.0: 1,
         392495.0: 1,
         105900.0: 1,
         440950.0: 1,
         241000.0: 1,
         209000.0: 1,
         268500.0: 1,
         256945.0: 1,
         88900.0: 1,
         349450.0: 1,
         98450.0: 1,
         180000.0: 2,
         86000.0: 1,
         152950.0: 2,
         263326.0: 1,
         123500.0: 1,
         186858.0: 1,
         397300.0: 1,
         290900.0: 1,
         184800.0: 1,
         228999.0: 1,
         211625.0: 1,
         319438.0: 1,
         157900.0: 1,
         500000.0: 1,
         211000.0: 1,
         282450.0: 1,
         249450.0: 2,
         224500.0: 1,
         186700.0: 1,
         93200.0: 1,
         87400.0: 1,
         167450.0: 1,
         422000.0: 1,
         125900.0: 1,
         123950.0: 1,
         478500.0: 1,
         92000.0: 1,
         396827.0: 1,
         314500.0: 1,
         373490.0: 1,
         324750.0: 1,
         253250.0: 1,
         179498.0: 1,
         329000.0: 1,
         237500.0: 1,
         280900.0: 3,
         332970.0: 1,
         75000.0: 1,
         166400.0: 1,
         148900.0: 2,
         287900.0: 1,
         274300.0: 1,
         206585.0: 1,
         177250.0: 1,
         233750.0: 1,
         165490.0: 1,
         152495.0: 1,
         317475.0: 1,
         426250.0: 1,
         133750.0: 1,
         296250.0: 1,
         148500.0: 1,
         156500.0: 1,
         140750.0: 1,
         203450.0: 1,
         227700.0: 1,
         309750.0: 1,
         374495.0: 1,
         328200.0: 1,
         151450.0: 1,
         201724.0: 1,
         438620.0: 1,
         184445.0: 1,
         382353.0: 1,
         176200.0: 1,
         198400.0: 1,
         347900.0: 1,
         243000.0: 1,
         92500.0: 2,
         187700.0: 1,
         114900.0: 1,
         188000.0: 1,
         244450.0: 1,
         220450.0: 1,
         248990.0: 1,
         360548.0: 1,
         89450.0: 1,
         164250.0: 1,
         237990.0: 1,
         191950.0: 1,
         147490.0: 1,
         143700.0: 2,
         450000.0: 1,
         244950.0: 2,
         407158.0: 1,
         274768.0: 1,
         211700.0: 1,
         167500.0: 1,
         174700.0: 1,
         126000.0: 1,
         89995.0: 1,
         111750.0: 1,
         214500.0: 1,
         176900.0: 1,
         413750.0: 1,
         144750.0: 1,
         247923.0: 1,
         268000.0: 1,
         292115.0: 1,
         260700.0: 1,
         256248.0: 1,
         177700.0: 1,
         319900.0: 1,
         237200.0: 1,
         152500.0: 1,
         398000.0: 2,
         171500.0: 1,
         362000.0: 1,
         335195.0: 1,
         154750.0: 1,
         119450.0: 1,
         177200.0: 1,
         196000.0: 1,
         354726.0: 1,
         249940.0: 1,
         324495.0: 1,
         192900.0: 1,
         371990.0: 1,
         291000.0: 1,
         264800.0: 1,
         394500.0: 1,
         394900.0: 1,
         307450.0: 1,
         281200.0: 1,
         197000.0: 1,
         122995.0: 1,

In [17]:
score = rf_model.score(X_train, y_train)
print("R-squared:", score)

R-squared: 0.9953110014184156

In [18]:
from sklearn.metrics import mean_squared_error
y_pred = rf_model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mse)
print("RMSE: ", mse*(1/2.0))

MSE:  231349567.05651823
RMSE:  115674783.52825911

In [ ]:
# dict of county names with values
#county_names = filter_df.County.unique()
#county_di = dict(zip(county_names, range(len(county_names))))
#county_di

In [ ]:
# county names with #'s'
#df_countynumber = df.copy()
#df_countynumber['County'].replace(county_di, inplace=True)
#df_countynumber.head()

In [ ]:
# heat map of feature correlation
plt.rcParams['figure.figsize']=35,35
g = sns.heatmap(df.corr(),annot=True, fmt = ".1f")

In [ ]:
# distribution plot of column
sns.distplot(df['median_listing_price'])

In [ ]:
# convert Price_class to numeric, distribution of median_listing_price increase|decrease month/month
df['Price_Status'] = df['Price_Status'].replace(['up','down'],['1','0'])
sns.distplot(df['Price_Status'])

In [ ]:
# Reference code for heatmaps :https://www.kaggle.com/code/bsivavenu/house-price-calculation-methods-for-beginners

# most correlated features
corrmat = df.corr()
top_corr_features = corrmat.index[abs(corrmat["median_listing_price"])>0.30]
plt.figure(figsize=(10,10))
g = sns.heatmap(df[top_corr_features].corr(),annot=True,cmap="mako")

In [ ]:
# seaborn linear regression fit: median listing price vs median square feet
sns.jointplot(data=df, x="median_listing_price", y="median_square_feet", kind="reg")

# outliers present

In [ ]:
#median_listing_price vs average listing price
sns.jointplot(data=df, x="median_listing_price", y="average_listing_price", kind="reg")

In [ ]:
# seaborn linear regression fit: median listing price vs median square feet
sns.jointplot(data=df, x="median_listing_price", y="violent_crime_rate", kind="reg")

In [ ]:
#median listing price vs Year
sns.jointplot(data=df, x="median_listing_price", y="Year", kind="reg")

In [ ]:
# Find Missing Ratio of Dataset
# reference: https://stackoverflow.com/questions/51070985/find-out-the-percentage-of-missing-values-in-each-column-in-the-given-dataset
#percent_missing = df.isnull().sum() * 100 / len(df)
#missing_value_df = pd.DataFrame({'column_name': df.columns,
                                 #'percent_missing': percent_missing})
#missing_value_df

In [ ]:
# reference
# https://www.kaggle.com/code/kanncaa1/machine-learning-tutorial-for-beginners/notebook
#https://www.kaggle.com/code/erick5/predicting-house-prices-with-machine-learning/notebook

In [ ]:
# dict of county names with values
#county_names = df.County.unique()
#county_di = dict(zip(county_names, range(len(county_names))))
#county_di

In [ ]:
# county names with #'s'
#df_new = df.copy()
#df_new['County'].replace(county_di, inplace=True)
#df_new.head()

In [ ]:
#df_new.to_csv("c:/tmp/courses.csv",header=False)

In [ ]:
# copy the data
#df_max_scaled = df_data.copy()
  
# apply normalization techniques
#for column in df_max_scaled.columns:
    #df_max_scaled[column] = df_max_scaled[column]  / df_max_scaled[column].abs().max()
      
# view normalized data
#display(df_max_scaled)